### ISSUE TITLE
Upgrade/Overhaul - tracking

### ISSUE THREAD

**Issue by leeallen337** [smashingboxes/web-boilerplate#64]
I'm going to plan on upgrading the boilerplate over the next few weeks in some of my spare time and this is going to be an issue tracking the upgrade

Tasks:
- [ ] Upgrade `webpack` & `webpack-dev-server`
- [ ] Upgrade `react` to v16.0+
- [ ] Include the `prop-types` package
- [ ] Upgrade `react-router` to `react-router-dom`
- [ ] Remove packages that are not needed anymore (e.g. `webpack-dev-middleware`)
- [ ] Implement Travis for pull requests to the boilerplate
- [ ] Protect `master`
- [ ] Upgrade `redux-persist`

**Comment by leeallen337** [comment]
Note: `redux-persist` v5 does not support an `ImmutableJS` object at the top level and the top level must be a POJO (Plain Old JavaScript Object). I'll be following the issue [here](https://github.com/rt2zz/redux-persist-immutable/issues/33) which allows us to have a top level `ImmutableJS` object in v4
